name: ci

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      - 
        name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: paracetamol32/nginxtest:${{ steps.vars.outputs.tag }},paracetamol32/nginxtest:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - 
        name: Update rancher deployment
        uses: th0th/rancher-redeploy-workload@v0.6
        env:
          RANCHER_BEARER_TOKEN: ${{ secrets.RANCHER_BEARER_TOKEN }}
          RANCHER_CLUSTER_ID: 'c-h5h8d'
          RANCHER_NAMESPACE: 'nginx'
          RANCHER_PROJECT_ID: 'p-s6rhf'
          RANCHER_URL: 'https://rancher.vecteur.it'
          RANCHER_WORKLOADS: 'nginx-deployment'
          RANCHER_DOCKER_REGISTRY: 'hub.docker.com'
          UPDATE_IMAGES: 'paracetamol32/nginxtest:latest'
