on:
  push:
    tags:
      - '*'
name: Publish Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          prerelease_regex: "^3\\.[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
